Make the tests pass with Sphinx 7.2
Starting with Sphinx 7.2, SphinxTestApp constructor expects srcdir to
be pathlib.Path. Otherwise, the following error happens:

    >       outdir.mkdir(parents=True, exist_ok=True)
    E       AttributeError: 'path' object has no attribute 'mkdir'